# Artificial Neural Network

### Importing the libraries

In [80]:
# Import necessary libraries
import tensorflow as tf
import numpy as np
import pandas as pd

In [81]:
print(tf.__version__)

2.15.0


## Part 1 - Data Preprocessing

Import dataset and assign to variables.

In [82]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [83]:
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


Encoding 'Gender'

In [84]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [85]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


Encoding 'Geography' (one hot encoding)
France -> 1 0 0
Spain -> 0 1 0
Germany -> 0 0 1

In [86]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [87]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splitting the dataset into the training and test dataset

In [88]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [89]:
X_train.shape

(8000, 12)

In [90]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

In [94]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 50, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 16, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 50, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

## Part 3 - Training the ANN

In [95]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics =['accuracy'])

In [96]:
ann.fit(X_train, y_train, batch_size = 64, epochs = 150)

Epoch 1/150
125/125 [==============================] - 1s 2ms/step - loss: 0.5185 - accuracy: 0.7790
Epoch 2/150
125/125 [==============================] - 0s 2ms/step - loss: 0.4422 - accuracy: 0.8066
Epoch 3/150
125/125 [==============================] - 0s 2ms/step - loss: 0.4277 - accuracy: 0.8171
Epoch 4/150
125/125 [==============================] - 0s 2ms/step - loss: 0.4175 - accuracy: 0.8225
Epoch 5/150
125/125 [==============================] - 0s 3ms/step - loss: 0.4107 - accuracy: 0.8249
Epoch 6/150
125/125 [==============================] - 0s 2ms/step - loss: 0.4055 - accuracy: 0.8274
Epoch 7/150
125/125 [==============================] - 0s 2ms/step - loss: 0.4014 - accuracy: 0.8314
Epoch 8/150
125/125 [==============================] - 0s 3ms/step - loss: 0.3983 - accuracy: 0.8313
Epoch 9/150
125/125 [==============================] - 0s 4ms/step - loss: 0.3941 - accuracy: 0.8342
Epoch 10/150
125/125 [==============================] - 0s 4ms/step - loss: 0.3911 - accura

In [61]:
print(y_train)

[0 0 0 ... 0 0 0]


## Part 4 - Making the predictions and evaluating the model

**Exam**

"Use our ANN model to predict if the customer with the
following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer ?"



In [69]:
print(X_test.shape)
print(y_test.shape)


(2000, 12)
(2000,)


In [70]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 127ms/step
[[False]]


##งานที่ 2: Predicting the Test set results ด้วยกลุ่มคำสั่ง:

In [71]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
# Reshape y_test to have 2 dimensions before concatenation
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test), 1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 1]
 [0 0]]


##งานที่ 3: สร้าง Confusion Matrix ด้วยกลุ่มคำสั่ง:

In [72]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1508   81]
 [ 234  177]]


0.8425

##งานที่ 1: ให้สร้างข้อมูลทดสอบ 5 ชุดที่แตกต่างกันเพื่อทำ Prediction จากโมเดลของตัวเอง

**Customer Profile 1 (France)**

Geography: France

Credit Score: 680

Gender: Male

Age: 50 years old

Tenure: 7 years

Balance: $55,000

Number of Products: 3

Credit Card: Yes

Active Member: Yes

Estimated Salary: $75,000

So, should we say goodbye to that customer ?"


**France -> 1 0 0 Spain -> 0 1 0 Germany -> 0 0 1**

In [73]:
print(ann.predict(sc.transform([[1, 0, 0, 680, 1, 50, 7, 55000, 3, 1, 1, 75000]])) > 0.5)

1/1 [==============================] - 0s 37ms/step
[[ True]]


**Customer Profile 2 (Germany)**

Geography: Germany

Credit Score: 720

Gender: Female

Age: 29 years old

Tenure: 4 years

Balance: $35,000

Number of Products: 2

Credit Card: Yes

Active Member: No

Estimated Salary: $50,000

So, should we say goodbye to that customer ?"

**France -> 1 0 0 Spain -> 0 1 0 Germany -> 0 0 1**

In [76]:
print(ann.predict(sc.transform([[0, 0, 1, 720, 0, 29, 4, 35000, 2, 1, 0, 50000]])) > 0.5)

1/1 [==============================] - 0s 21ms/step
[[False]]


**Customer Profile 3 (Spain)**

Geography: Spain

Credit Score: 610

Gender: Male

Age: 38 years old

Tenure: 6 years

Balance: $70,000

Number of Products: 1

Credit Card: No

Active Member: Yes

Estimated Salary: $55,000

So, should we say goodbye to that customer ?"

**France -> 1 0 0 Spain -> 0 1 0 Germany -> 0 0 1**

In [77]:
print(ann.predict(sc.transform([[0, 1, 0, 610, 1, 38, 6, 70000, 1, 0, 1, 55000]])) > 0.5)

1/1 [==============================] - 0s 116ms/step
[[False]]


**Customer Profile 4 (France)**

Geography: France

Credit Score: 630

Gender: Female

Age: 45 years old

Tenure: 3 years

Balance: $20,000

Number of Products: 2

Credit Card: Yes

Active Member: No

Estimated Salary: $65,000

So, should we say goodbye to that customer ?"

**France -> 1 0 0 Spain -> 0 1 0 Germany -> 0 0 1**

In [78]:
print(ann.predict(sc.transform([[1, 0, 0, 630, 0, 45, 3, 20000, 2, 1, 0, 65000]])) > 0.5)

1/1 [==============================] - 0s 34ms/step
[[False]]


**Customer Profile 5 (Germany)**

Geography: Germany

Credit Score: 700

Gender: Male

Age: 55 years old

Tenure: 10 years

Balance: $90,000

Number of Products: 4

Credit Card: Yes

Active Member: Yes

Estimated Salary: $100,000

So, should we say goodbye to that customer ?"

**France -> 1 0 0 Spain -> 0 1 0 Germany -> 0 0 1**

In [79]:
print(ann.predict(sc.transform([[0, 0, 1, 700, 1, 55, 10, 90000, 4, 1, 1, 100000]])) > 0.5)

1/1 [==============================] - 0s 43ms/step
[[ True]]
